### ISSUE TITLE
Composer playground stuck on loading screen.

### ISSUE THREAD

**Issue by RTZ229** [IBM/hyperledger-fabric-on-linux-one#28] opened 2018-07-04 05:07 UTC
![screen shot 2018-07-04 at 10 31 01 am](https://user-images.githubusercontent.com/17705162/42257711-8d4b9800-7f75-11e8-963a-e0f9c23f6172.png)
OS : mac os x 10.13.5
composer running on IBM LinuxOne community cloud server
Where exactly are these files in which the errors are poping up. 
please can anyone who has done some work on LinuxOne suggest a way to get the composer up and running. It's very urgent.

Thanks.

**Comment by ztanaka1971** [comment] 2018-07-06 07:03
I have exactly same issue. Load of following files stops at halfway ...

http://148.100.108.118:8080/main.054debceeae0e1e2dd1e.bundle.js
http://148.100.108.118:8080/vendor.656f8780869d6045fcda.bundle.js
http://148.100.108.118:8080/polyfills.eb7a9fefe827db0c2516.bundle.js

**Comment by vmorris** [comment] 2018-07-06 12:33
What component of composer, playground?
What version of composer?
What version of node?
What version of npm?
Did you try to reinstall the npm package?

**Comment by ztanaka1971** [comment] 2018-07-06 23:59
I found it's not only Hyperledger Composer, but HTTP communication of other programs has similar problem on the community cloud (I tried Angular tutorial and experienced same problem). I also found that this problem doesn't occur if I use SSH port forwarding from localhost to http server on LinuxONE instance.

Anyway, I tried Composer Playground v0.19.8 and v0.19.12, both has same symptom. node v8.11.2, npm v5.6.0.
I deleted/re-created LinuxONE instance, then installed all packages again, but same symptom persists.

**Comment by SweetJenn23** [comment] 2018-07-07 00:32
I've never had a problem running Composer Playground. I can try to start it up at the latest versions. I usually use SLES and not RHEL on LinuxONE Community Cloud. @ztanaka1971  what OS on CommunityCloud are you using? 

I (we) have never been able to get Angular working on the Community Cloud. It seems to be something in how the system is setup. I've mentioned this to the team but have never made them work through it with me.

**Comment by SweetJenn23** [comment] 2018-07-07 01:12
I've duplicated the problem and have reached out to the Community Cloud team. @ztanaka1971 , I'll keep you posted on what I get back.

**Comment by SweetJenn23** [comment] 2018-07-11 21:08
@RTZ229 How are you doing? I've been escalating. My best guess is it's a network issue. When we are logged in to Marist (who hosts LinueONE Community Cloud) the page loads fine. Outside of their network, it doesn't. I'm not sure what's changed.

**Comment by SweetJenn23** [comment] 2018-07-12 00:07
@RTZ229 @ztanaka1971 this is now fixed. You should no longer have any issues with Composer Playground not loading.

**Closed by SweetJenn23** 2018-07-12 00:07 UTC

**Comment by ztanaka1971** [comment] 2018-07-12 00:36
Thank you !! I also confirmed I can open Composer Playground on my instance.
